import {
  API_URL as ENV_API_URL,
  STRIPE_PUBLIC_KEY as ENV_STRIPE_PUBLIC_KEY,
  MAPBOX_API_KEY as ENV_MAPBOX_API_KEY,
  MAPBOX_API_URL as ENV_MAPBOX_API_URL,
} from "@env";

const API_URL = ENV_API_URL;
const STRIPE_PUBLIC_KEY = ENV_STRIPE_PUBLIC_KEY;
const MAPBOX_API_KEY = ENV_MAPBOX_API_KEY;
const MAPBOX_API_URL = ENV_MAPBOX_API_URL;

export { API_URL, MAPBOX_API_URL, MAPBOX_API_KEY, STRIPE_PUBLIC_KEY };
