import React from "react";
import type { AppProps } from "next/app";
import type { Page } from "../types/page";
import Head from "next/head";
import { AppProvider } from "@/provider";
import { Guard } from "@/components";
import { Toaster } from "react-hot-toast";

type Props = AppProps & {
  Component: Page;
};

export default function App({ Component, pageProps }: Props) {
  const getLayout = Component?.getLayout || ((page) => page);
  const Layout = getLayout(<Component {...pageProps} />);
  const layout = React.isValidElement(Layout) ? Layout : <>{Layout}</>;

  return (
    <>
      <Head>
        <title>FRENCHIES SPOTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
        />
        <meta name="description" content="Description" />
        <meta name="keywords" content="Keywords" />
        <title>FRENCHIES-SPOTS</title>

        <link rel="manifest" href="/manifest.json" />
      </Head>
      <main
        style={{
          height: "100vh",
          margin: 0,
          padding: 0,
        }}
      >
        <AppProvider>
          {layout}
          <Toaster />
        </AppProvider>
      </main>
    </>
  );
}
